name: Add new docset to contrib repository
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      debug:
        description: 'Deebug flag (if true, no commits are pushed)'
        required: false
        type: boolean
        default: true
jobs:
  push:
    name: Push to contrib repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: get version
        id: version
        run: |
          version=$(cat .version | sed -e "s/v//")
          echo ::set-output "name=version::$version"
      - name: clone upstream master
        run: |
          git clone --branch master https://github.com/Kapeli/Dash-User-Contributions.git contrib
          cd contrib
          git checkout -b optuna-${{ steps.version.outputs.version }}
          cd ..
      # - uses: actions/checkout@v2
      #   with:
      #     repository: Kapeli/Dash-User-Contributions
      #     path: contrib
      #     persist-credentials: false
      - name: update archives
        run: |
          mkdir ./contrib/docsets/Optuna/versions/${{ steps.version.outputs.version }}
          tar --exclude='.DS_Store' -cvzf Optuna.tgz Optuna.docset
          cp Optuna.tgz ./contrib/docsets/Optuna/
          cp Optuna.tgz ./contrib/docsets/Optuna/versions/${{ steps.version.outputs.version }}
      - name: update docset.json
        run: |
          docset_json=contrib/docsets/Optuna/docset.json
          jq --arg version ${{ steps.version.outputs.version }} '
          .version=$version | 
          .specific_versions = [
              {
                "version": $version, 
                "archive": ("versions/" + $version + "/Optuna.tgz")
              }
            ] + .specific_versions' $docset_json > $docset_json
      - name: commit
        run: |
          cd contrib
          git config --global user.email "${{ secrets.CI_USER_EMAIL }}"
          git config --global user.name  "${{ secrets.CI_USER_USERNAME }}"
          git add -A
          git commit -m "update Optuna docset to ${{ steps.version.outputs.version }}"
      - name: push
        if:  ${{ github.event.inputs.debug != 'true' }}
        run: |
          git push \
            "https://${{ secrets.CI_USER_USERNAME }}:${{ secrets.CI_USER_ACCESS_TOKEN }}@github.com/29Takuya/Dash-User-Contributions.git" \
            HEAD:optuna-${{ steps.version.outputs.version }}
      - name: push (dry-run)
        if:  ${{ github.event.inputs.debug == 'true' }}
        run: |
          git push -n \
            "https://${{ secrets.CI_USER_USERNAME }}:${{ secrets.CI_USER_ACCESS_TOKEN }}@github.com/29Takuya/Dash-User-Contributions.git" \
            HEAD:optuna-${{ steps.version.outputs.version }}
